version: '3.7'

services:
  cmsfe:
    image: node:12.2.0-alpine
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: Dockerfile
    networks:    
      - outside